apiVersion: stack.zncdata.net/v1alpha1
kind: SparkHistoryServer
metadata:
  labels:
    app.kubernetes.io/name: sparkhistoryserver
    app.kubernetes.io/instance: sparkhistoryserver
    app.kubernetes.io/part-of: spark-k8s
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: spark-k8s-operator
  name: sparkhistoryserver-sample
spec:
  image:
    repository: bitnami/spark
    tag: 3.1.1
    pullPolicy: IfNotPresent
  service:
    port: 18080
    type: ClusterIP
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
    host: spark-history-server.example.com
  persistence:
    enable: true
#    existingClaim: sparkhistoryserver-sample
#    storageClassName:
    accessMode: ReadWriteOnce
    storageSize: 1Gi
    volumeMode: Filesystem
  roleGroups:
    default:
      replicas: 1
      config:
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
  selectors:
    default:
      selector:
        matchLabels:
          app: sparkhistoryserver
  roleConfig:
    eventLog:
        enabled: true
        mountMode: pvc
        dir: /tmp/spark-events
  securityContext:
    runAsUser: 1000
    fsGroup: 1000